name: chempilot

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - rdkit
  - pip:
      - PyTDC
      - matplotlib
      - numpy
      - pandas
      - pyarrow
      - PyYAML
      - scikit-learn
      - seaborn
      - setuptools<81
      - tqdm
      - joblib
      - pytest
      - xgboost
      - torch==2.6.0
      - torch_geometric==2.8.0.post1
